@baseUrl = http://localhost:8088
@auth = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDYwMjIwMzAsInVzZXJuYW1lIjoiZGV2MDEiLCJuYW1lIjoiZGV2IGRldiJ9.FW613xlE7PJm_PADLFE9r65toXuuvl7q6cV7Pi_Lj7dEAfnQ4-fSJDlicS79k-s6rqtV835xV9nGmM1UEgl-VPAO_4syy-LpXjzJL2eRNFmMg3Cy1jp_RYY-mlHvshfVyCRqh6ZDbe_9lUKZ1avYjqjF9fjFWPB4IRF53kiYz3hIVbu3hAsbEYoQhH32sSdYtgF5aaa78XLH3c9BG3KHKWUpE4LU2bJp5NcDL2JT9NBRXZ8slMjHW0JGGh5oSnt2yYFJDSyWY1K8Z6tYnG4pY9of_qSfRzAM_KHBLoVTReYOLXIHfRpUe8VPHiwLvjG7Tn1VocLkCqpaZYxYv6iJtlHMkmx5RXs8QYCDWmrgUeqEhrGiIxU-VDKI5wa6YG1f1QcHVjEC461lpjtaytSfxPn_Jq_XfqEUBBERnQFESuOUCPmQUHgHLQYPS-Xoqxu5zcKweXfoSUvNfX0NqSTviaif4lv7J44iWijDcL3JqmDCdRx7xK02BSdI7TMTqw1u0-h5HegrPeKp2I7k3BGiEB76TkUW0O4nR1CigEKz0onD0_yeQkQv1zi_esi7zy1UlWmIlNfKzbZj6DmLNbgjbKZ0A_FaOi80zUdaVPEgPuzRj4Y7LuqpLszq7uHRQ9_MNdnT6jttY8GJy5Wli0j5gKqdeQdFWcqxogDs8UEQbCQ
@shopID = 25H2pZ8v2jRVGwjOLKBAzSaHgOA
@memberID = 61c15e0a42ab5650fb0adb41


# @name login
POST {{baseUrl}}/login 
Content-Type: application/json

{
    "username": "dev01",
    "password": "dev"
}

###
POST {{baseUrl}}/shop
Authorization: {{auth}}
Content-Type: application/json

{
    "name1": "shop new"
}

###
GET {{baseUrl}}/shop
Authorization: {{auth}}
Content-Type: application/json

###
GET {{baseUrl}}/shop/{{shopID}}
Authorization: {{auth}}
Content-Type: application/json

###
PUT {{baseUrl}}/shop/{{shopID}}
Authorization: {{auth}}
Content-Type: application/json

{
    "name1": "shop new 1"
}

###
DELETE {{baseUrl}}/shop/{{shopID}}
Authorization: {{auth}}
Content-Type: application/json


###
GET {{baseUrl}}/shop/{{shopID}}/member
Authorization: {{auth}}
Content-Type: application/json

###
POST {{baseUrl}}/shop/{{shopID}}/member
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "shop 1",
    "email": "email2@mail.com",
    "username": "user1",
    "password": "password"
}

###
GET {{baseUrl}}/shop/{{shopID}}/member/{{memberID}}
Authorization: {{auth}}
Content-Type: application/json

###

PUT {{baseUrl}}/shop/{{shopID}}/member/{{memberID}}
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "testaaa modify",
    "email": "testaaa@hotmail.com",
    "username": "aaa"
}

###

PUT {{baseUrl}}/shop/{{shopID}}/member/{{memberID}/password
Authorization: {{auth}}
Content-Type: application/json

{
    "password": "aaaaaaa"
}

###

DELETE {{baseUrl}}/shop/{{shopID}}/member/{{memberID}}
Authorization: {{auth}}
Content-Type: application/json
