version: '3.8'

services:
  redis:
    image: bitnami/redis:5.0
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - 6379:6379
    networks:
       - backend
  mongodb:
    image: bitnami/mongodb:5.0
    container_name: mongodbdev
    volumes:
      - ./mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017
    environment:
#      - MONGODB_ROOT_USERNAME=smlmgdb
      - MONGODB_ROOT_PASSWORD=smlmgdb
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
    networks:
      - backend
  postgresql:
    container_name: postgresql
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sml
    networks:
       - backend

networks:
  backend:
    external:
      name: sml_service_backend