version: '3.8'

services:
  swaggerapi:
    image: smlsoft/smlcloudplatform:swagger
    expose:
      - 8080
    environment:
      - SERVER_PORT=8080
    networks:
      - frontend
    labels:
      - "traefik.http.routers.swagger.rule=(PathPrefix(`/swagger`))"
networks:
  frontend:
    external:
      name: sml_service_frontend