version: 2.1
orbs:
  docker: circleci/docker@2.1.2
  k8s: digitalocean/k8s@0.1.1
jobs:
  build-and-push:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          # deploy: false
          #dockerfile: Dockerfile-K8S
          image: smlsoft/smlcloudplatform
          #use-docker-credentials-store: true
          tag: apidev
      - docker/push:
          image: smlsoft/smlcloudplatform
          tag: apidev
          
  deploy-dev:
    executor: docker/machine
    steps:
      - checkout
      - k8s/install
      - k8s/initialize:
          cluster: 916a438e-9629-4798-8a7e-c5e31acb5b99
      - run: kubectl rollout restart deployment/dedepos-dev-api deployment/dedepos-dev-consume -n dedepos-dev
  
workflows:
  build-dev-only:
    jobs:
      - build-and-push:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - develop
      - deploy-dev:
          requires:
            - build-and-push
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - develop
  build-prod:
    jobs:
      - build-prod-docker:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - release
      - deploy-prod-cluster:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - release
