definitions:
  models.Barcode:
    properties:
      barcode:
        type: string
      unit_code:
        type: string
    type: object
  models.Inventory:
    properties:
      barcodes:
        $ref: '#/definitions/models.Barcode'
      code:
        type: string
      image_uri:
        type: string
      latest_update:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: info@smlcloudplatform.io
    name: API Support
    url: http://www.smlcloudplatform.io
  description: This Api for Manage Product For SMLCloudPlatform
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ProductAPI
  version: "1.0"
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Inventory'
            type: array
      summary: Fetch Product
      tags:
      - Inventory
swagger: "2.0"
