version: '3.8'

services:
  cloud_authentication:
    image: smlsoft/smlcloudplatform:authen-1.0
    expose:
      - 8080
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://localhost:27017/
      - MONGODB_DB=smldev
      - REDIS_CACHE_URI=localhost:6379
    networks:
      - frontend
      - backend


networks:
  frontend:
    external:
      name: sml_service_frontend
  backend:
    external:
      name: sml_service_backend