version: '3.8'

services:
  inventory:
    image: smlsoft/smlcloudplatform:masterdata
    restart: always
    expose:
      - 8080
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB=smldev
      - REDIS_CACHE_URI=redis:6379
    labels:
      - "traefik.http.routers.masterdata.rule=(PathPrefix(`/inventory`) || PathPrefix(`/option`) || PathPrefix(`/optgroup`) || PathPrefix(`/category`) || PathPrefix(`/member`))"
    networks:
#      - frontend
      - backend

networks:
#  frontend:
#    external:
#      name: sml_service_frontend
  backend:
    external:
      name: sml_service_backend