version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - backend
  kafka: 
    image: bitnami/kafka:3.1.0
    container_name: kafka
    restart: always
#    ports:
#      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

      # - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      # - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      # - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      # # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # - KAFKA_NUM_NETWORK_THREADS=8
      # - KAFKA_NUM_IO_THREADS=16
    networks:
      - backend
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 200M

networks:
  backend:
    external:
      name: sml_service_backend