// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/category": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "List Inventory Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Value",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Add Category",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Add Category",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Create Inventory Option",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "description": "Option",
                        "name": "Option",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InventoryOption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/category/{id}": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Get Inventory Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Update Inventory",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Category",
                        "name": "Category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Category"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Delete Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/inventory": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "get struct array by ID",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Inventory"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Create Inventory",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "description": "Inventory",
                        "name": "Inventory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Inventory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/inventory/{id}": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "get struct array by ID",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Inventory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Inventory"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Update Inventory",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Inventory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Inventory",
                        "name": "Inventory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Inventory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Delete Inventory",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Inventory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/list-shop": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "List Merchant In My Account",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ShopUserInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "get struct array by ID",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "parameters": [
                    {
                        "description": "User Account",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponseFailed"
                        }
                    }
                }
            }
        },
        "/member": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "List Member Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Value",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Create Member",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "description": "Member",
                        "name": "Member",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Member"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/member/{id}": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Get Member Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Member Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Update Member",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Member ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Member",
                        "name": "Member",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Member"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Delete Member",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Member ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/merchant": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Access to Merchant",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Merchant"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ShopInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/optgroup": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "List Inventory Option Group",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Value",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Size",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Create Inventory Option Group",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "description": "Option Group",
                        "name": "Option",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InventoryOptionGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/optgroup/{id}": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Get Option Group Information",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "OptionGroup Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Update Option Group",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Option ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Option Group",
                        "name": "OptionGroup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InventoryOptionGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Delete OptionGroup",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "OptionGroup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/option": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "List Inventory Option",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Value",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Add Category",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Add Category",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/option/{id}": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Get Inventory Option",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Option Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Update Option",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Option ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Option",
                        "name": "Option",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InventoryOption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Delete Option",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Option ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "For User Register Application",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register An Account",
                "parameters": [
                    {
                        "description": "Register account",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseSuccessWithID"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponseFailed"
                        }
                    }
                }
            }
        },
        "/select-shop": {
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Access to Shop",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "parameters": [
                    {
                        "description": "Shop",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ShopSelectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            }
        },
        "/shop": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Access to Shop",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Shop"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ShopInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Create Shop",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Shop"
                ],
                "parameters": [
                    {
                        "description": "Add Shop",
                        "name": "Shop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Shop"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Shop"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseSuccessWithID"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "id": {},
                "message": {
                    "type": "string"
                },
                "pagination": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.AuthResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.AuthResponseFailed": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.Category": {
            "type": "object",
            "properties": {
                "guidFixed": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name1": {
                    "type": "string"
                },
                "name2": {
                    "type": "string"
                },
                "name3": {
                    "type": "string"
                },
                "name4": {
                    "type": "string"
                },
                "name5": {
                    "type": "string"
                },
                "shopID": {
                    "type": "string"
                }
            }
        },
        "models.Choice": {
            "type": "object",
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "name1": {
                    "type": "string"
                },
                "name2": {
                    "type": "string"
                },
                "name3": {
                    "type": "string"
                },
                "name4": {
                    "type": "string"
                },
                "name5": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "qty": {
                    "type": "integer"
                },
                "suggestCode": {
                    "type": "string"
                }
            }
        },
        "models.Inventory": {
            "type": "object",
            "properties": {
                "activated": {
                    "description": "เปิดใช้งานอยู่",
                    "type": "boolean"
                },
                "barcode": {
                    "type": "string"
                },
                "categoryGuid": {
                    "description": "Guid กลุ่มสินค้า",
                    "type": "string"
                },
                "description1": {
                    "description": "รายละเอียดภาษาไทย",
                    "type": "string"
                },
                "description2": {
                    "type": "string"
                },
                "description3": {
                    "type": "string"
                },
                "description4": {
                    "type": "string"
                },
                "description5": {
                    "type": "string"
                },
                "guidFixed": {
                    "description": "Guid สินค้า",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "itemSku": {
                    "type": "string"
                },
                "memberPrice": {
                    "type": "number"
                },
                "name1": {
                    "description": "ชื่อภาษาไทย",
                    "type": "string"
                },
                "name2": {
                    "type": "string"
                },
                "name3": {
                    "type": "string"
                },
                "name4": {
                    "type": "string"
                },
                "name5": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Option"
                    }
                },
                "price": {
                    "description": "ราคาพื้นฐาน (กรณีไม่มีตารางราคา และโปรโมชั่น)",
                    "type": "number"
                },
                "recommended": {
                    "description": "สินค้าแนะนำ",
                    "type": "boolean"
                },
                "shopID": {
                    "description": "รหัสร้าน",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "unitName1": {
                    "type": "string"
                },
                "unitName2": {
                    "type": "string"
                },
                "unitName3": {
                    "type": "string"
                },
                "unitName4": {
                    "type": "string"
                },
                "unitName5": {
                    "type": "string"
                }
            }
        },
        "models.InventoryOption": {
            "type": "object",
            "properties": {
                "guidFixed": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inventoryID": {
                    "type": "string"
                },
                "optionGroupID": {
                    "type": "string"
                },
                "shopID": {
                    "type": "string"
                }
            }
        },
        "models.InventoryOptionGroup": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.InventoryOptonGroupDetail"
                    }
                },
                "guidFixed": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "optionName1": {
                    "type": "string"
                },
                "productSelectOptionMax": {
                    "type": "integer"
                },
                "productSelectOptionMin": {
                    "type": "integer"
                },
                "productSelectoPtion1": {
                    "type": "boolean"
                },
                "productSelectoPtion2": {
                    "type": "boolean"
                },
                "shopID": {
                    "type": "string"
                }
            }
        },
        "models.InventoryOptonGroupDetail": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "detailName1": {
                    "type": "string"
                },
                "guidFixed": {
                    "type": "string"
                }
            }
        },
        "models.Member": {
            "type": "object",
            "properties": {
                "TaxID": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "branchCode": {
                    "type": "string"
                },
                "branchType": {
                    "type": "integer"
                },
                "contactType": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "personalType": {
                    "type": "integer"
                },
                "surname": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string"
                }
            }
        },
        "models.Option": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Choice"
                    }
                },
                "code": {
                    "type": "string"
                },
                "maxSelect": {
                    "type": "integer"
                },
                "name1": {
                    "type": "string"
                },
                "name2": {
                    "type": "string"
                },
                "name3": {
                    "type": "string"
                },
                "name4": {
                    "type": "string"
                },
                "name5": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "selectMode": {
                    "type": "string"
                }
            }
        },
        "models.ResponseSuccessWithID": {
            "type": "object",
            "properties": {
                "id": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.Shop": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "default": "-"
                },
                "name1": {
                    "type": "string"
                }
            }
        },
        "models.ShopInfo": {
            "type": "object",
            "properties": {
                "guidFixed": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name1": {
                    "type": "string"
                }
            }
        },
        "models.ShopSelectRequest": {
            "type": "object",
            "properties": {
                "shopID": {
                    "type": "string"
                }
            }
        },
        "models.ShopUserInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "shopID": {
                    "type": "string"
                }
            }
        },
        "models.UserRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "minLength": 3
                }
            }
        }
    },
    "securityDefinitions": {
        "AccessToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "SML Cloud Platform API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
