name: Git Sha
on: [workflow_dispatch]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: smlsoft/smlcloudapi

jobs:
  update-mainfest-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: smlsoft/sml-ols-cluster-config
          ref: 'main'
          token: ${{ secrets.GH_SECRET }}
      - name: setup git config
        run: |
          git config --global user.email "woranich@gmail.com"
          git config --global user.name "userplant"
          echo ${{ github.sha }}
          echo ${GITHUB_SHA::7}
          sed -i "s|ghcr.io/smlsoft/smlcloudapi:sha-.\{7\}|ghcr.io/smlsoft/smlcloudapi:sha-${GITHUB_SHA::7}|g" /dedepos-api-dev/deployment.yaml
          git add -A
          git commit -am "Update dedepos-api-dev sha-${GITHUB_SHA::7}"
      - run: echo ${{ github }}
      - run: git push origin master
  
