name: Git Sha
on: [workflow_dispatch]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: smlsoft/smlcloudapi

jobs:
  update-mainfest-stage:
    runs-on: ubuntu-latest
    env:
        SHA7: ${GITHUB_SHA::7}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup git config
        run: |
          echo ${{ github.sha }}
          echo $SHA7
